# Site settings
title: MJ.Dev
default_author: MinJun.Ju
description: "Hello World"  # used in site head

# register on google analytics and replace this token
google_analytics: UA-75681059-1
# disque comments are broken if you send http:// along with url, this url is same as the one given on disqus
# Deleting the value would remove it from footer.
disqus_url: disqus.com/by/minjunju 
disqus_id: minjujublog
# register on feedburner and replace this url. Deleting the value will remove it from footer.
feedburner_url: #https://feedburner.google.com/fb/a/mailverify?uri=programmer-wannabe&amp;loc=en_US

# footer details. Deleting the value would remove it from footer.
github_username:  juuminjun
facebook_username:  https://www.facebook.com/JU89664111
email: juuminjun@gmail.com
stackoverflow_username: https://stackoverflow.com/users/8601335/minjun-ju?tab=profile
#twitter_username : shikherverma42
#linkedin_username : shikherverma42
#keybase_username : shikherverma
copyright_name: MJ.Dev
rss : false

# used for portfolio on home page
collections:
  - portfolio

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
